name: yellowfivedesign
favicon: null
layout_spectrum: 0.25035
typography_spectrum: 0.63494
title: Yellow Five Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8b8b8b'
    - '#16101d'
    - '#40332e'
    - '#605952'
    - '#9da099'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
