name: yellowfivedesign
favicon: null
layout_spectrum: 0.62053
typography_spectrum: 0.47579
title: Yellow Five Design
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8b8b8b'
    - '#16101d'
    - '#40332e'
    - '#605952'
    - '#9da099'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
